Repository minio/minio-go, pull requests merged in 2024-02, with the labels that each got.

#1927 Enable --expired-object-all-versions
  pkg/lifecycle/lifecycle.go
Labels: bugfix, needs review

#1934 Drop seeding rand in tests
  core_test.go
Labels: community, bugfix

#1935 Make 520 status code retryable
  retry.go
Labels: community

#1942 Drop more rand seeding in tests
  core_test.go
Labels: community
